# Generated by Django 5.0.4 on 2024-05-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('data_count', models.IntegerField()),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pass_count', models.IntegerField()),
                ('language_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mathematics_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('english_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chemistry_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('physics_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('biology_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('geography_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('politics_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('history_score', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'unique_together': {('year', 'province', 'city')},
            },
        ),
    ]
