# Generated by Django 5.0.4 on 2024-05-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScoreStatistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorestatistics',
            name='biology_score',
            field=models.DecimalField(decimal_places=2, max_digits=65),
        ),
        migrations.AlterField(
            model_name='scorestatistics',
            name='chemistry_score',
            field=models.DecimalField(decimal_places=2, max_digits=65),
        ),
        migrations.AlterField(
            model_name='scorestatistics',
            name='english_score',
            field=models.DecimalField(decimal_places=2, max_digits=65),
        ),
        migrations.AlterField(
            model_name='scorestatistics',
            name='geography_score',
            field=models.DecimalField(decimal_places=2, max_digits=65),
        ),
        migrations.AlterField(
            model_name='scorestatistics',
            name='history_score',
            field=models.DecimalField(decimal_places=2, max_digits=65),
        ),
        migrations.AlterField(
            model_name='scorestatistics',
            name='language_score',
            field=models.DecimalField(decimal_places=2, max_digits=65),
        ),
        migrations.AlterField(
            model_name='scorestatistics',
            name='mathematics_score',
            field=models.DecimalField(decimal_places=2, max_digits=65),
        ),
        migrations.AlterField(
            model_name='scorestatistics',
            name='physics_score',
            field=models.DecimalField(decimal_places=2, max_digits=65),
        ),
        migrations.AlterField(
            model_name='scorestatistics',
            name='politics_score',
            field=models.DecimalField(decimal_places=2, max_digits=65),
        ),
        migrations.AlterField(
            model_name='scorestatistics',
            name='total_score',
            field=models.DecimalField(decimal_places=2, max_digits=65),
        ),
    ]
