# Generated by Django 5.0.4 on 2024-05-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('language', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mathematics', models.DecimalField(decimal_places=2, max_digits=5)),
                ('english', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chemistry', models.DecimalField(decimal_places=2, max_digits=5)),
                ('physics', models.DecimalField(decimal_places=2, max_digits=5)),
                ('biology', models.DecimalField(decimal_places=2, max_digits=5)),
                ('geography', models.DecimalField(decimal_places=2, max_digits=5)),
                ('politics', models.DecimalField(decimal_places=2, max_digits=5)),
                ('history', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
